language: go

go:
- 1.12.x
- 1.13.x

env:
  global:
  - GO111MODULE=on

before_install:
- go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@latest

script:
- make

after_success:
- bash <(curl -s https://codecov.io/bash)
