
[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/ini.v1"
  version = "1.33.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.2.0"

[prune]
  go-tests = true
  unused-packages = true
